### ISSUE TITLE
Problem with STIX2.1 nested object reference

### ISSUE THREAD

**Issue by Lastrellik** [oasis-open/cti-python-stix2#419] opened 2020-06-24 17:43 UTC
When creating a NetworkTraffic object with a nested HTTPRequestExt object where message_body_data_ref references an Artifact object, we get some strange behavior with what that message_body_data_ref resolves to with the STIX2.1 library. To demonstrate this problem, look at the following script:
```python
from stix2.v21 import ObservedData, Artifact, HTTPRequestExt, NetworkTraffic, IPV4Address
from datetime import datetime

def build_http_intel():
    http_version='http/1.1'
    request_method='get'
    request_value='/carolebaskin'
    http_referrer = 'http://referer.com'
    http_content_type = 'text/html; charset=utf-8'
    user_agent = 'Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0'
    status_code = '200 OK'
    cookie = '$Version=1; Skin=new;'
    artifact = Artifact(url='http://foo.bar.baz/path?derp=purp', hashes={'MD5': 'c157a79031e1c40f85931829bc5fc552'}) 
    header = {
        'Host': 'foo.bar',
        'Pragma': 'no-cache',
        'Referer': http_referrer,
        'Content-Type': http_content_type,
        'User-Agent': user_agent,
        'Status': status_code,
        'cookie': cookie
    }
    src_ip = IPv4Address(value='1.1.1.1')
    # This line is where the problem is 
    http_request = HTTPRequestExt(request_method=request_method, request_version=http_version, request_value=request_value, request_header=header, message_body_data_ref=artifact) #  This is where we have a problem
    # This line is where the problem is ^^
    traffic = NetworkTraffic(
        extensions={
            'http-request-ext': http_request
        },
        protocols=['tcp'],
        src_ref=src_ip
    )
    http_observables={
        "0": src_ip,
        "1": artifact,
        "2": traffic
    }
    observed_data = ObservedData(first_observed=datetime.now(), last_observed=datetime.now(), number_observed=1, objects=http_observables)
    return observed_data

http_intel = build_http_intel()
print(http_intel)
```
We would expect the output of this to be something like this:
```javascript
       {
            "type": "observed-data",
            "spec_version": "2.1",
            "id": "observed-data--922d0cd9-2a20-4658-ad5e-1e107c5dbbf4",
            "created": "2020-06-24T17:37:08.098044Z",
            "modified": "2020-06-24T17:37:08.098044Z",
            "first_observed": "2020-06-24T10:37:08.098031Z",
            "last_observed": "2020-06-24T10:37:08.098033Z",
            "number_observed": 1,
            "objects": {
                "0": {
                    "type": "ipv4-addr",
                    "id": "ipv4-addr--646b2d04-bb90-595c-9299-5f0995ae684d",
                    "spec_version": "2.1",
                    "value": "1.1.1.1"
                },
                "1": {
                    "type": "artifact",
                    "id": "artifact--2c545bc0-7f81-5c8c-b3c0-b49487eb4da6",
                    "spec_version": "2.1",
                    "url": "http://foo.bar.baz/path?derp=purp",
                    "hashes": {
                        "MD5": "c157a79031e1c40f85931829bc5fc552"
                    }
                },
                "2": {
                    "type": "network-traffic",
                    "id": "network-traffic--da9e8659-71cc-556e-b9a8-dbc17817dfc8",
                    "spec_version": "2.1",
                    "src_ref": "ipv4-addr--646b2d04-bb90-595c-9299-5f0995ae684d",
                    "protocols": [
                        "tcp"
                    ],
                    "extensions": {
                        "http-request-ext": {
                            "request_method": "get",
                            "request_value": "/carolebaskin",
                            "request_version": "http/1.1",
                            "request_header": {
                                "Content-Type": "text/html; charset=utf-8",
                                "Host": "foo.bar",
                                "Pragma": "no-cache",
                                "Referer": "http://referer.com",
                                "Status": "200 OK",
                                "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0",
                                "cookie": "$Version=1; Skin=new;"
                            },
                            "message_body_data_ref": "artifact--2c545bc0-7f81-5c8c-b3c0-b49487eb4da6"
                        }
                    }
                }
            }
        }
```
But we actually get something like this. Notice the "message_body_data_ref" data inside of network-traffic.extensions.http-request-ext.message_body_data_ref

```javascript
        {
            "type": "observed-data",
            "spec_version": "2.1",
            "id": "observed-data--922d0cd9-2a20-4658-ad5e-1e107c5dbbf4",
            "created": "2020-06-24T17:37:08.098044Z",
            "modified": "2020-06-24T17:37:08.098044Z",
            "first_observed": "2020-06-24T10:37:08.098031Z",
            "last_observed": "2020-06-24T10:37:08.098033Z",
            "number_observed": 1,
            "objects": {
                "0": {
                    "type": "ipv4-addr",
                    "id": "ipv4-addr--646b2d04-bb90-595c-9299-5f0995ae684d",
                    "spec_version": "2.1",
                    "value": "1.1.1.1"
                },
                "1": {
                    "type": "artifact",
                    "id": "artifact--2c545bc0-7f81-5c8c-b3c0-b49487eb4da6",
                    "spec_version": "2.1",
                    "url": "http://foo.bar.baz/path?derp=purp",
                    "hashes": {
                        "MD5": "c157a79031e1c40f85931829bc5fc552"
                    }
                },
                "2": {
                    "type": "network-traffic",
                    "id": "network-traffic--da9e8659-71cc-556e-b9a8-dbc17817dfc8",
                    "spec_version": "2.1",
                    "src_ref": "ipv4-addr--646b2d04-bb90-595c-9299-5f0995ae684d",
                    "protocols": [
                        "tcp"
                    ],
                    "extensions": {
                        "http-request-ext": {
                            "request_method": "get",
                            "request_value": "/carolebaskin",
                            "request_version": "http/1.1",
                            "request_header": {
                                "Content-Type": "text/html; charset=utf-8",
                                "Host": "foo.bar",
                                "Pragma": "no-cache",
                                "Referer": "http://referer.com",
                                "Status": "200 OK",
                                "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0",
                                "cookie": "$Version=1; Skin=new;"
                            },
                            "message_body_data_ref": "{\n    \"type\": \"artifact\",\n    \"id\": \"artifact--2c545bc0-7f81-5c8c-b3c0-b49487eb4da6\",\n    \"url\": \"http://foo.bar.baz/path?derp=purp\",\n    \"hashes\": {\n        \"MD5\": \"c157a79031e1c40f85931829bc5fc552\"\n    },\n    \"spec_version\": \"2.1\"\n}"
                        }
                    }
                }
            }
        }

```

For the record, we do not see this behavior with the STIX2.0 library

**Comment by emmanvg** [comment] 2020-06-24 22:25
Hi @Lastrellik, this issue has been identified, fixed and staged for our next release (duplicate of #396). When the next release is out your code should behave as expected. I will close this issue since there is no action at this point.

---

Feel free to reopen if you think the issue has not addressed.

**Closed by emmanvg** 2020-06-24 22:25 UTC
