### ISSUE TITLE
TypeError: Object of type ThreatActor is not JSON serializable

### ISSUE THREAD

**Issue by m0jtaba** [oasis-open/cti-python-stix2#125] opened 2018-02-02 02:32 UTC
Have I missed something fundamental here, trying to push stix content but getting "TypeError: Object of type ThreatActor is not JSON serializable"

```
from stix2 import TAXIICollectionSink, ThreatActor
from taxii2client import Collection
import json
collection = Collection("http://127.0.0.1:5000/trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/", user="admin", password="Password0")

#create TAXIICollectionSINK and push STIX content to it
tc_sink = TAXIICollectionSink(collection)

# create new STIX threat-actor
ta = ThreatActor(name="Teddy Bear",
                labels=["nation-state"],
                sophistication="innovator",
                resource_level="government",
                goals=[
                    "compromising environment NGOs",
                    "water-hole attacks geared towards energy sector",
                ])

tc_sink.add(ta)

**Comment by gtback** [comment] 2018-02-02 14:45
Hi, @m0jtaba . We clearly have a lot to do in terms of specifying exactly what types of things the sink can accept, and where exactly to draw the line of responsibility between the `Collection` in `taxii2client` and the `TAXIICollectionSink` in `stix2`. I thought I might be able to provide a workaround without hacking into the guts of either library, but I can't figure it out. We do have a plan for reworking both libraries to make this much more straightforward, but until we have a chance to work on that I'm not sure if I have a good answer. Sorry :-( 

@mbastian1135 , @clenk am I missing something?

**Comment by mbastian1135** [comment] 2018-02-02 16:23
So its been a while and correct me if Im wrong, but tc.add() triggers a conversion to a bundle, then gets cast as a python dict. Then the dict is passed to collection.add_objects() which just passes the dict to a requests post. So is this a json load happening in bundle() (i.e. the sink) or something that is happening in the Collection ? Although I dont know where it would be in Collection... And if its the former why is ThreatActor not serializable?

@m0jtaba Stack trace available?

**Comment by m0jtaba** [comment] 2018-02-02 17:24
@gtback thanks for taking a look. I just want to make sure that I am clear with what I am trying to achieve.  My goal is to have a TAXII Server receive a STIX2 object from a TAXII Client and currently  I'm using memory backend. Also to convert none STIX2 objects into STIX2 objects using the STIX2 API and pushing the STIX2 object into a TAXII Server via the TAXII Client.


@mbastian1135 see below:
```

python3.4 clientSink.py 

Traceback (most recent call last):
  File "clientSink.py", line 20, in <module>
    tc_sink.add(ta)
  File "/usr/lib/python3.4/site-packages/stix2/sources/taxii.py", line 81, in add
    self.collection.add_objects(bundle)
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 342, in add_objects
    status_json = self._conn.post(self.objects_url, headers=headers, json=bundle)
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 588, in post
    resp = self.session.post(url, headers=headers, params=params, json=json)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 458, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib/python3.4/site-packages/simplejson/__init__.py", line 382, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.4/site-packages/simplejson/encoder.py", line 293, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.4/site-packages/simplejson/encoder.py", line 678, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python3.4/site-packages/simplejson/encoder.py", line 635, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python3.4/site-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python3.4/site-packages/simplejson/encoder.py", line 698, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.4/site-packages/simplejson/encoder.py", line 268, in default
    o.__class__.__name__)
TypeError: Object of type ThreatActor is not JSON serializable
```

Valid JSON when you print it
print(ta):
```
{
    "type": "threat-actor",
    "id": "threat-actor--6219eb0e-627c-433c-a7d2-f5b1ebb4c6e9",
    "created": "2018-02-01T01:16:09.082Z",
    "modified": "2018-02-01T01:16:09.082Z",
    "name": "Teddy Bear",
    "goals": [
        "compromising environment NGOs",
        "water-hole attacks geared towards energy sector"
    ],
    "sophistication": "innovator",
    "resource_level": "government",
    "labels": [
        "nation-state"
    ]
}
```

print(json.dumps(ta)) :
```
TypeError: ThreatActor(type='threat-actor', id='threat-actor--c02b4f34-0ad0-4687-a7e7-aa5d02de2012', created='2018-02-01T01:15:05.767Z', modified='2018-02-01T01:15:05.767Z', name='Teddy Bear', goals=['compromising environment NGOs', 'water-hole attacks geared towards energy sector'], sophistication='innovator', resource_level='government', labels=['nation-state']) is not JSON serializable
```

**Comment by chisholm** [comment] 2018-02-03 20:02
> So its been a while and correct me if Im wrong, but tc.add() triggers a conversion to a bundle, then gets cast as a python dict. Then the dict is passed to collection.add_objects() which just passes the dict to a requests post. So is this a json load happening in bundle() (i.e. the sink) or something that is happening in the Collection ? Although I dont know where it would be in Collection... And if its the former why is ThreatActor not serializable?

- Calling `dict()` on something does a shallow conversion to a dict, and doesn't do any type conversions.  Therefore, the result isn't guaranteed to be JSON-serializable (with the default conversion table).  For taxii2-client to be able to handle what stix2 passes it, it would need a custom encoder.  Stix2 actually has one, but I don't know that taxii2-client was intended to have stix2 as a dependency.  And anyway, I'm not sure if it's possible to tell `requests` to use a custom encoder to encode/decode HTTP request/response bodies (I haven't looked).  It might not be.
- From the above, it follows that `print(json.dumps(ta))` isn't going to work, since the `json` module doesn't know anything about the stix2 classes.  It would need to be given a custom encoder.  The following produces better results:
    ```python
    from stix2.base import STIXJSONEncoder
    import json

    # (create stix2 object)

    print(json.dumps(ta, cls=STIXJSONEncoder))
    ```

**Comment by gtback** [comment] 2018-02-05 14:52
`STIXJSONEncoder` is not exactly public; the intended way to do this is to call the `[serialize()]()https://github.com/oasis-open/cti-python-stix2/blob/a790d8f5616e2b2a113be0e29dd711b37abeeb07/stix2/base.py#L180)` function, which does that for you.

Unfortunately, the TAXIICollectionSink and TAXII client don't currently use this, so I'm not aware of a workaround. Eventually, I'd like the TAXII client to accept an (already-`dumps`-ed) string, and the TAXIICollectionSink in python-stix2 to do the serialization with the `serialize` function.

**Comment by m0jtaba** [comment] 2018-02-05 16:13
@gtback  So removing the TAXIICollectionSink in python-stix2 from my example above, how would you just use the TAXII client to post an object?  if possible, can you please provide an example?

**Comment by chisholm** [comment] 2018-02-05 16:16
Ah, right.  So I guess a silly workaround (untested!) would be to serialize, then parse as plain JSON.  E.g. `tc_sink.add(json.loads(Bundle(ta).serialize()))`.  (Gotta bundle the sdo before serialization, otherwise it looks like the add method will bundle the sdo itself and do the same, incorrect shallow-dictification, resulting in the same "ThreatActor not JSON serializable" error.)

**Comment by chisholm** [comment] 2018-02-05 16:26
You ought to be able to invoke taxii2-client directly too, in a similar way (again, untested): `my_collection.add_objects(json.loads(Bundle(ta).serialize()))`

This needs to be better.  Round-tripping through a string seems wasteful, but the alternative is implementing a deep-dictification, similar to old python-stix's to_dict() method?

**Comment by mbastian1135** [comment] 2018-02-05 17:37
So there isnt a dunder method/magic I dont know about that can override the dict() call, i.e. conceptually a "__dict__" that can be put in STIXBase? As dict() only needs a sequence of key/values, and as long as its a valid dict, it should be json serializable (dict->obj).  Leaving all dict conversion within python-stix?

Or couldn't you use STIXBase.serialize() but in reverse?

**Comment by chisholm** [comment] 2018-02-05 18:18
Yeah, there's nothing like a `__dict__` method you can implement to change how `dict()` behaves, as far as I know.  So we can't be that clever :)

>as long as its a valid dict, it should be json serializable

I may misunderstand what you said, but not all dicts are JSON-serializable (with the default conversion table).  That's the problem.  The types of the keys and values matters.  Within our own stix2 library, we can get fancy with the custom encoders and support additional types as JSON-serializable content, but across library boundaries, that doesn't work.  Other libraries don't have our encoder, and can't handle the stix2 object types (unless they're specifically designed to); they require the plain stock types which have support built into the `json` library.  Taxii2-client falls into that category: it has no special support for stix2 types.

**Comment by mbastian1135** [comment] 2018-02-05 18:44
Right, yep. I was more thinking about that as long as we manage to give dict() a sequence of "normal" keys/values, including through all the nested layers, it seems like it should always be json serializable with the default table. That was assuming we could efficiently and recursively do that, i.e. I havnt put much thought into the intricacies beyond a simple TA object.

**Comment by m0jtaba** [comment] 2018-02-05 22:55
@chisholm I tried both of your suggestion and got a better result considering:

tc_sink.add(json.loads(Bundle(threatActor).serialize()))
```
Traceback (most recent call last):
  File "clientSink.py", line 30, in <module>
    tc_sink.add(json.loads(Bundle(threatActor).serialize()))
  File "/usr/lib/python3.4/site-packages/stix2/sources/taxii.py", line 81, in add
    self.collection.add_objects(bundle)
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 337, in add_objects
    self._verify_can_write()
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 281, in _verify_can_write
    if not self.can_write:
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 248, in can_write
    self._ensure_loaded()
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 274, in _ensure_loaded
    self.refresh()
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 285, in refresh
    response = self._conn.get(self.url, accept=MEDIA_TYPE_TAXII_V20)
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 578, in get
    raise TAXIIServiceException(msg.format(content_type))
taxii2client.TAXIIServiceException: Unexpected Response Content-Type: application/vnd.oasis.stix+json; version=2.0
```

collection.add_objects(json.loads(Bundle(threatActor).serialize()))
```
Traceback (most recent call last):
  File "clientSink.py", line 31, in <module>
    collection.add_objects(json.loads(Bundle(threatActor).serialize()))
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 337, in add_objects
    self._verify_can_write()
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 281, in _verify_can_write
    if not self.can_write:
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 248, in can_write
    self._ensure_loaded()
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 274, in _ensure_loaded
    self.refresh()
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 285, in refresh
    response = self._conn.get(self.url, accept=MEDIA_TYPE_TAXII_V20)
  File "/usr/lib/python3.4/site-packages/taxii2client/__init__.py", line 578, in get
    raise TAXIIServiceException(msg.format(content_type))
taxii2client.TAXIIServiceException: Unexpected Response Content-Type: application/vnd.oasis.stix+json; version=2.0
```

**Comment by gtback** [comment] 2018-02-06 14:36
I tried the workaround that @chisholm suggested when I was initially looking for a temporary solution. The problem is that, even when you serialize the object yourself to a string, the TAXIICollectionSink will parse the string back into objects and try to serialize again (this is what we need to change!)

I was able to make progress by running `collection.add_objects(Bundle(ta).serialize())`, but this was then causing problems in the medallion server.

**Comment by m0jtaba** [comment] 2018-02-06 15:20
@chisholm @gtback I might have something here based on all of your suggestions. The issue I was having with [this](https://github.com/oasis-open/cti-python-stix2/issues/125#issuecomment-363249497) has been resolved by removing the "/objects/"  from api path and it has successfully made a connection to the taxii server and posted the the threat actor and when you get the objects back it's all there:
```
from stix2 import ThreatActor, Bundle, Indicator
from taxii2client import Collection
import json

collection = Collection("http://127.0.0.1:5000/trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/", user="admin", password="Password0")


# create new STIX threat-actor
threatActor = ThreatActor(name="Teddy Bear",
                labels=["nation-state"],
                sophistication="innovator",
                resource_level="government",
                goals=[
                    "compromising environment NGOs",
                    "water-hole attacks geared towards energy sector",
                ])

indicator = Indicator(name="File hash for malware variant",
                      labels=["malicious-activity"],
                      pattern="[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']")

collection.add_objects(json.loads(Bundle(threatActor, indicator).serialize()))

print(collection.get_objects())
```

Partial output of collection.get_objects():
```
{  
         'id':'threat-actor--bd695924-80de-4911-8c2b-92b4785856ea',
         'name':'Teddy Bear',
         'sophistication':'innovator',
         'created':'2018-02-05T23:31:09.428Z',
         'modified':'2018-02-05T23:31:09.428Z',
         'resource_level':'government',
         'type':'threat-actor',
         'labels':[  
            'nation-state'
         ],
         'goals':[  
            'compromising environment NGOs',
            'water-hole attacks geared towards energy sector'
         ]
}
```
Server logs:
```
127.0.0.1 - - [06/Feb/2018 01:57:47] "POST /trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/objects/ HTTP/1.1" 202 -
127.0.0.1 - - [06/Feb/2018 01:57:47] "GET /trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/objects/ HTTP/1.1" 200 -
```

I believe for what I want to achieve this will be a workable. I don't see any issues with continuing with the workaround by not using TAXIICollectionSink,  what do you guys think?

**Comment by chisholm** [comment] 2018-02-06 17:30
> I tried the workaround that @chisholm suggested when I was initially looking for a temporary solution. The problem is that, even when you serialize the object yourself to a string, the TAXIICollectionSink will parse the string back into objects and try to serialize again (this is what we need to change!)

My solution was not only to serialize to a string, but to `json.loads()` it back to a dict again.  The code looked like it would pass the dict through unchanged.  So... even uglier!  But I think it worked.

>  The issue I was having with this has been resolved by removing the "/objects/" from api path and it has successfully made a connection to the taxii server and posted threat actor and when you get the objects back it's all there:

Oh, so you had instantiated the `Collection` object using a URL with "/objects/" already appended.  Hmmm, maybe the documentation could use improvement.  Yeah, instantiate the collection with the URL for a particular collection; other stuff is appended to the URL path depending on what you want to do with it.  E.g. appending "objects/" for adding or getting objects; "manifest/" for getting the manifest, etc.

**Comment by mbastian1135** [comment] 2018-03-13 16:23
Whats the status of this? After re-reading the thread, it looks like we need to make some changes to TAXIICollectionSink.add(), even if just to reduce what repeated processing we can as well have the interface actually work.

**Comment by gtback** [comment] 2018-03-14 15:17
(I believe) the long term solution is to make the `taxii2client.Collection.add_objects()` function accept a string (already serialized JSON) rather than a dictionary, and then update the `TAXIICollectionSink.add()` function to take the `stix2.ThreatActor` object as input and call `serialize()` on it to provide what `Collection.add_objects()` expects. 

For now, working around the TAXIICollectionSink and using the taxii2client directly may be the best option.

**Comment by Voronsky** [comment] 2018-03-14 16:07
Greetings,

 I am new to this repo but I've been playing around this to further understand how TAXII works. As @m0jtaba  mentioned, I followed the documentation and came to that exact error mentioned in the first post. His workaround worked for me and for the time being will help me move along.  Will the docs be updated to reflect the issue presented here?

**Comment by gtback** [comment] 2018-03-14 16:54
👋 Hi @Voronsky. Thanks for the suggestion.

@clenk, can you update the documentation until we have a chance to fix this?

**Comment by clenk** [comment] 2018-03-15 22:08
@gtback I've added a note to the documentation.

**Comment by emmanvg** [comment] 2018-03-21 14:49
@m0jtaba and @Voronsky, can you pull the latest changes from `cti-python-stix2`, `cti-taxii-client` and `cti-taxii-server` (if applicable) and verify if you still experience the same behavior? Otherwise, we can close this issue.

**Comment by gtback** [comment] 2018-03-21 15:28
I just tested with the latest cti-python-stix2. This error is no longer happening. The actual upload fails down the line for a different reason in cti-taxii-server, but we can go ahead and close this issue.

**Closed by gtback** 2018-03-21 15:28 UTC
