### ISSUE TITLE
Error when compiled using pyinstaller

### ISSUE THREAD

**Issue by Tomasinjo** [oasis-open/cti-python-stix2#218] opened 2018-10-28 11:28 UTC
Hi,
I have some issues when compiled with pyinstaller. Output:
  File "attack_parse.py", line 28, in mapping
    Filter('relationship_type','=','mitigates') # find only techniques
  File "site-packages\stix2\datastore\__init__.py", line 98, in query
  File "site-packages\stix2\datastore\filesystem.py", line 323, in query
  File "site-packages\stix2\datastore\filesystem.py", line 323, in <listcomp>
  File "site-packages\stix2\core.py", line 100, in parse
  File "site-packages\stix2\core.py", line 133, in dict_to_stix2
KeyError: 'v20'
[14740] Failed to execute script attack_parse

**Comment by clenk** [comment] 2018-10-31 21:17
Hi @Tomasinjo. This is caused by https://github.com/pyinstaller/pyinstaller/issues/1905 and [this line in our code](https://github.com/oasis-open/cti-python-stix2/blob/3084c9f51fcd00cf6b0ed76827af90d0e86746d5/stix2/core.py#L176). The workaround is to create a file called `hook-stix2.py` with the following contents:

```python
import os
from PyInstaller.utils.hooks import get_module_file_attribute

stix2_dir = os.path.dirname(get_module_file_attribute('stix2'))
datas = [(stix2_dir, 'stix2')]
```

Then when you compile with pyinstaller, use the `--additional-hooks-dir=.` option (assuming `hook-stix2.py` is in the same directory).

I'm closing this but if it doesn't work for you feel free to reopen!

**Closed by clenk** 2018-10-31 21:17 UTC
