### ISSUE TITLE
Artifact object requiring "hashes" property by error

### ISSUE THREAD

**Issue by Lastrellik** [oasis-open/cti-python-stix2#413] opened 2020-06-17 16:52 UTC
According to https://stix2.readthedocs.io/en/latest/api/v20/stix2.v20.observables.html#stix2.v20.observables.Artifact none of the properties for Artifact are required: 
```
Properties:	
mime_type (String)
payload_bin (Binary)
url (String)
hashes (Hashes)
extensions (Extensions)
```
However, when instantiating the Artifact object with:
```python
from stix2 import Artifact

artifact = Artifact(url='http://foo.bar')
```
results in
```
The property dependencies for Artifact: (hashes, url) are not met
```

It seems weird for "hashes" to be a required property

**Comment by emmanvg** [comment] 2020-06-17 19:21
Hi @Lastrellik, you are correct in all properties being optional under the Artifact definition for STIX 2.0. Now, if you read at the description for each of the fields there are additional requirements that are mandated such as:

>hashes (optional) - Specifies a dictionary of hashes for the contents of the **url** or the **payload_bin**.  This **MUST** be provided when the **url** property is present.

Reference: http://docs.oasis-open.org/cti/stix/v2.0/cs01/part4-cyber-observable-objects/stix-v2.0-cs01-part4-cyber-observable-objects.html#_Toc496716218

----
I will close this since this is the intended behavior. Feel free to reopen if you feel the issue has not been addressed.

**Closed by emmanvg** 2020-06-17 19:21 UTC
