### ISSUE TITLE
EmailMIMEComponet body_raw_ref issue

### ISSUE THREAD

**Issue by Lastrellik** [oasis-open/cti-python-stix2#421] opened 2020-07-06 19:14 UTC
Hello,
In the STIX2 observables library for the EmailMIMEComponent, when trying to add a reference to an Artifact or a File object like this:
```python
from stix2 import EmailMIMEComponent, Artifact, File

attachment_type = 'application/pdf'
attachment_binary = b'ZW1haWwgYXR0YWNobWVudCBjb250ZW50cwo='
hashes = {
    'MD5': 'ffa4344d434659d6fc69eca166f870a7',
    'SHA1': '0e518dcead742e7127345d15ca7eba694b50d0fa'
}
artifact = Artifact(hashes=hashes, payload_bin=attachment_binary, mime_type=attachment_type)

email_mime_component_attachment = EmailMIMEComponent(
    _valid_refs={
        "0": artifact
    },
    body_raw_ref="0"
)

print(email_mime_component_attachment)
```

We get an error saying
```
stix2.exceptions.ExtraPropertiesError: Unexpected properties for EmailMIMEComponent: (_valid_refs)
```

However, when I modify the script as such: 
```python
from stix2 import EmailMIMEComponent, Artifact, File

attachment_type = 'application/pdf'
attachment_binary = b'ZW1haWwgYXR0YWNobWVudCBjb250ZW50cwo='
hashes = {
    'MD5': 'ffa4344d434659d6fc69eca166f870a7',
    'SHA1': '0e518dcead742e7127345d15ca7eba694b50d0fa'
}
artifact = Artifact(hashes=hashes, payload_bin=attachment_binary, mime_type=attachment_type)

email_mime_component_attachment = EmailMIMEComponent(
    body_raw_ref=artifact # this is mainly what changed
)

print(email_mime_component_attachment)
```

We get this incorrect result:
```
{
    "body_raw_ref": "{\n    \"type\": \"artifact\",\n    \"mime_type\": \"application/pdf\",\n    \"payload_bin\": \"ZW1haWwgYXR0YWNobWVudCBjb250ZW50cwo=\",\n    \"hashes\": {\n        \"MD5\": \"ffa4344d434659d6fc69eca166f870a7\",\n        \"SHA-1\": \"0e518dcead742e7127345d15ca7eba694b50d0fa\"\n    }\n}"
}
```
Where we expect the references in body_raw_ref to be references instead of this stringified json. This seems like a bug

**Comment by emmanvg** [comment] 2020-07-06 21:28
Hi @Lastrellik, as you may have noticed we recently made a new release of the library `v2.0.1`. Can you update and check since this issue has already been resolved (duplicate of #396). I should also mention:

- The examples you are showing me are using two different versions of the spec. You need to stick with one STIX 2.0 or STIX 2.1 and this library support both versions.
- By default, after v2.0.0 the library will now load the **2.1** version of the object. If you want to use STIX 2.0 then perform the following change in your code `from stix2.v20 import EmailMIMEComponent, Artifact, File`.
- If you are going to use STIX 2.0, the following should be enough to stop the `stix2.ExtraPropertiesError` from occurring.

``` python
from stix2.v20 import EmailMIMEComponent, Artifact, File

attachment_type = 'application/pdf'
attachment_binary = b'ZW1haWwgYXR0YWNobWVudCBjb250ZW50cwo='
hashes = {
    'MD5': 'ffa4344d434659d6fc69eca166f870a7',
    'SHA1': '0e518dcead742e7127345d15ca7eba694b50d0fa'
}
artifact = Artifact(hashes=hashes, payload_bin=attachment_binary, mime_type=attachment_type)

email_mime_component_attachment = EmailMIMEComponent(
    body_raw_ref="0"  # The _valid_refs dict is only available for objects that subclass _Observable it is not available for use here. Although, you do want to make sure you are providing the correct reference to this object.
)

print(email_mime_component_attachment)
```
Provides
```
{
    "body_raw_ref": "0"
}
```

Hope this helps!

**Comment by Lastrellik** [comment] 2020-07-06 22:54
@emmanvg when I upgraded to stix 2.0.1 and run your exact script, I get this `ModuleNotFoundError: No module named 'six.moves.collections_abc'` error from `/virtual_environments/stix/lib/python3.7/site-packages/stix2/versioning.py", line 9, in <module>` is this a known issue here or am I missing something?

**Comment by emmanvg** [comment] 2020-07-06 23:35
ah! make sure you update the six dependency as well... `pip install --upgrade six`

**Closed** 2020-07-07 13:32 UTC
