### ISSUE TITLE
Improve code coverage/testing of TAXIICollection

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-python-stix2#148] opened 2018-03-28 13:27 UTC
We talked about this on PR #143 and certainly it is important to improve the quality of the code under `stix2/datastore/taxii.py`. Some of the options available include:

- Create another test-environment for `stix2` that include the `taxii2client` and `medallion`:
    - In here, we could have the option to download the latest PyPI release available or download and install directly from the repositories.
        - If we use the releases of PyPI we might need to include additional test data under `stix2` for medallion.
        - If we download directly from the repo we might be able to use the test data already contained in the `test\` directory of `medallion`.
     - Use @treyka approach to allow for automated testing. It may require encrypting such credential values for Travis CI.

Any other thoughts on how to approach this or if any of the options above are preferred @clenk, @gtback, @chisholm, @mbastian1135 ?

**Comment by emmanvg** [comment] 2018-03-28 13:31
@treyka's approach is to use https://ubertaxii.com (Medallion-based) as part of the testing harness.

**Comment by clenk** [comment] 2018-03-28 17:01
I like the first option. We could use fixtures, similar to [this SO answer](https://stackoverflow.com/a/13375383/).

**Comment by gtback** [comment] 2018-03-28 21:15
I would also prefer the first option. Relying on external services is a recipe for confusion, uncertainly, and things outside our control. I hadn't thought about using pytest fixtures to launch a medallion process.

This is another reason to take the `test/` directory out from under `stix2/`. We don't need to be including all this test data in the public PyPI release.

**Comment by clenk** [comment] 2018-03-28 21:41
I believe we already exclude `test/` from our PyPI releases: https://github.com/oasis-open/cti-python-stix2/blob/master/setup.py#L47 Moving the directory might make this more obvious, however.

**Comment by clenk** [comment] 2018-04-02 18:23
Is this a duplicate of #64?

**Comment by emmanvg** [comment] 2018-04-02 18:28
This one is more oriented towards TAXII, but in general I would say yes. I plan to add tests to the other datastores too.

**Comment by emmanvg** [comment] 2018-04-03 16:31
I misread, yeah it is the same...

**Closed** 2018-04-24 20:12 UTC
